# Generated by Django 5.2.1 on 2025-12-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_setting_task_orderitem_earn_code_user_balance_and_more'),
    ]

    operations = [
        # First add new fields
        migrations.AddField(
            model_name='user',
            name='kyc_reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, max_length=20, null=True),
        ),
        # Migrate data: set kyc_status='approved' for users with is_kyc=True
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('core', 'User').objects.filter(is_kyc=True).update(kyc_status='approved'),
            reverse_code=lambda apps, schema_editor: None,
        ),
        # Then remove old field
        migrations.RemoveField(
            model_name='user',
            name='is_kyc',
        ),
    ]
