# Generated by Django 5.2.1 on 2025-12-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_replace_is_kyc_with_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='esewa_number',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='khalti_number',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='user',
            name='esewa_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='khalti_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='users/payment/qr/'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
