# Generated by Django 5.2.1 on 2025-12-17 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_withdrawal_esewa_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Alert when stock falls below this quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        # Note: StockMovement and StockAlert models were removed from models.py
        # but were never created in the database, so no deletion operations needed
    ]
