# Generated by Django 5.2.1 on 2025-12-17 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stock_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Alert when product stock falls below this quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
    ]
