# Generated by Django 6.0 on 2025-12-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='footer_section',
            field=models.CharField(blank=True, choices=[('customer_service', 'Customer Service'), ('information', 'Information')], help_text='Select which footer section this page should appear in', max_length=20, null=True),
        ),
    ]
