# Generated by Django 6.0 on 2025-12-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cmspage_footer_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address', null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL', null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
    ]
