# Generated by Django 6.0 on 2026-01-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_setting_address_setting_email_setting_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Track if stock was deducted when order was delivered and paid'),
        ),
    ]
