# Generated by Django 6.0 on 2026-01-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_flashdeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=100, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Charge',
                'verbose_name_plural': 'Shipping Charges',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='user_refer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount credited to influencer when they refer a new user', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_setting_reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_setting_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='core.shippingcharge'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.shippingcharge'),
        ),
    ]
