# Generated by Django 6.0 on 2026-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_setting_active_referal_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='user_refer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount credited to IBO when they refer a new user', max_digits=10),
        ),
    ]
